# Generated by Django 4.0.6 on 2022-11-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='oskars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
