# Generated by Django 4.0.6 on 2022-11-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0002_alter_actor_oskars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я автора")),
                ('second_name', models.CharField(blank=True, max_length=50, verbose_name='По батькові автора')),
                ('surname', models.CharField(max_length=50, verbose_name='Прізвище автора')),
                ('birth_date', models.DateField(verbose_name='Дата народження')),
                ('country', models.CharField(max_length=50, verbose_name='Країна походження')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автори',
                'ordering': ('birth_date',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва книги')),
                ('publication_date', models.DateField(verbose_name='Дата публікації')),
                ('number_of_pages', models.PositiveIntegerField(default=None, null=True, verbose_name='Кількість сторінок')),
                ('genre', models.CharField(choices=[('фікшн', 'Фікшн'), ('роман', 'Роман'), ('комедія', 'Комедія'), ('новела', 'Новела'), ('проза', 'Проза'), ('поезія', 'Поезія'), ('історична література', 'Історична література'), ('автобіографія', 'Автобіографія')], max_length=50, verbose_name='Жанр книги')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_4.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва видавництва')),
                ('country', models.CharField(max_length=50, verbose_name='Країна видавництва')),
                ('motto', models.TextField(blank=True, default=None, max_length=150, verbose_name='Гасло компанії')),
                ('established', models.DateField(verbose_name='Дата заснування')),
            ],
            options={
                'verbose_name': 'Видавництво',
                'verbose_name_plural': 'Видавництва',
                'ordering': ('established',),
            },
        ),
        migrations.AlterField(
            model_name='actor',
            name='films',
            field=models.ManyToManyField(to='lesson_4.film'),
        ),
        migrations.CreateModel(
            name='BookInStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна екземпляру')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість екземплярів')),
                ('language', models.CharField(choices=[('UA', 'Українська'), ('EN', 'Англійська'), ('FR', 'Французька'), ('DE', 'Німецька')], max_length=50, verbose_name='Мова видання')),
                ('number_of_pages', models.PositiveIntegerField(blank=True, default=None, verbose_name='Кількість сторінок')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_4.book', verbose_name='')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_4.publishinghouse', verbose_name='Видавництво')),
            ],
            options={
                'verbose_name': 'Екземпляри книги',
                'verbose_name_plural': 'Екземпляри книжок',
                'ordering': ('quantity',),
            },
        ),
    ]
