# Generated by Django 4.0.6 on 2022-11-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0003_author_book_publishinghouse_alter_actor_films_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='По батькові автора'),
        ),
        migrations.AlterField(
            model_name='bookinstore',
            name='number_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Кількість сторінок'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='motto',
            field=models.TextField(blank=True, default='', max_length=150, verbose_name='Гасло компанії'),
        ),
    ]
