# Generated by Django 4.0.6 on 2022-11-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0004_alter_author_second_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number_of_pages',
        ),
    ]
