# Generated by Django 4.0.6 on 2022-11-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0005_remove_book_number_of_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishinghouse',
            name='motto',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Гасло компанії'),
        ),
    ]
