# Generated by Django 4.0.6 on 2022-11-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0006_alter_publishinghouse_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='По батькові автора'),
        ),
    ]
