# Generated by Django 4.0.6 on 2022-11-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0007_alter_author_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstore',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_4.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookinstore',
            name='number_of_pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість сторінок'),
        ),
    ]
