# Generated by Django 4.0.6 on 2022-11-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0008_alter_bookinstore_book_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstore',
            options={'ordering': ('add_to_store_date',), 'verbose_name': 'Екземпляри книги', 'verbose_name_plural': 'Екземпляри книжок'},
        ),
        migrations.AddField(
            model_name='bookinstore',
            name='add_to_store_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
