# Generated by Django 4.0.6 on 2022-11-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0009_alter_bookinstore_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstore',
            name='add_to_store_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата надходження'),
        ),
    ]
