# Generated by Django 4.1.3 on 2022-12-05 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Товар')),
                ('image', models.ImageField(blank=True, upload_to='static/lesson_5/product/', verbose_name='Зображення')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Ціна')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255, verbose_name='Текст коментаря')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_5.product')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
            },
        ),
    ]
